apiVersion: v1 
kind: Service
metadata:
  name: {{ .Values.postgres.name}}
  labels: 
    name: {{ .Values.postgres.name}}
    app: {{ .Values.postgres.labels-app}}
spec:
  ports:
  - port: {{ .Values.postgres.port}}
    targetPort: {{ .Values.postgres.port}}
  selector:
    name: {{ .Values.postgres.labels-name}}
    app: {{ .Values.postgres.labels-app}}