apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Values.redis.name}}
  labels: 
    app: {{ .Values.redis.labels-app}}
spec:
  replicas: {{ .Values.redis.replicas}}
  selector: 
    matchLabels:
      name: {{ .Values.redis.labels-name}}
      app: {{ .Values.redis.labels-app}}
  template:
    metadata:
      name: {{ .Values.redis.labels-name}}
      labels: 
        name: {{ .Values.redis.labels-name}}
        app: {{ .Values.redis.labels-app}}
    spec:
      containers:
        - name: {{ .Values.redis.name}}
          image: {{ .Values.redis.image}}
          ports:
            - containerPort: {{ .Values.redis.port}}